### Create
POST http://localhost:8080/employees
Content-Type: application/json

{
  "employee_id": "Dev-002",
  "department_id": 1,
  "name": "Fachran Sandi",
  "address": "56 Cilangkap Jakarta Timur"
}

### Get All
GET http://localhost:8080/employees

### Get By ID
GET http://localhost:8080/employees/11

### Update
PUT http://localhost:8080/employees/11
Content-Type: application/json

{
  "employee_id": "ENG-002",
  "department_id": 2,
  "name": "Fachran Sandi Update",
  "address": "90 Cilangkap Jakarta Timur"
}

### Delete
DELETE http://localhost:8080/employees/1
